### PR TITLE
Suppress child updates in ExpandableGroup when collapsed. Fixes #56

### LINKED ISSUE #56: Support UpdatingGroup inside ExpandableGroup
Using an `UpdatingGroup` as a child of an `ExpandableGroup` seems to cause the following error:

```
E/UncaughtException: java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{2fe4242 position=30 id=-1, oldPos=5, pLpos:5 scrap [attachedScrap] tmpDetached no parent}
                          at android.support.v7.widget.RecyclerView$Recycler.validateViewHolderForOffsetPosition(RecyclerView.java:5046)
                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5177)
                          at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5158)
                          at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2061)
                          at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1445)
                          at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1408)
                          at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:580)
                          at android.support.v7.widget.RecyclerView.dispatchLayoutStep1(RecyclerView.java:3330)
                          at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3186)
                          at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3632)
```

I noticed that `UpdatingGroup` dispatches updates even though the `ExpandableGroup` is collapsed, which is probably the issue. I've solved this by passing a boolean flag (`dispatchUpdates`) to `UpdatingGroup.update` which is set to true if the `ExpandableGroup` is expanded. This seems to work, although there might be a better solution.

### PR DESCRIPTION
**Pull request by lisawray**

### CODE REVIEW

File: groupie/src/main/java/com/genius/groupie/ExpandableGroup.java [hunk 1]
```diff
@@ -64,4 +64,71 @@ public void onToggleExpanded() {
             notifyItemRangeInserted(oldSize, newSize - oldSize);
         }
     }
+    
+    private boolean dispatchChildChanges(Group group) {
```
Comment (kjpublic01) [inline groupie/src/main/java/com/genius/groupie/ExpandableGroup.java]: A little late to the party, but another possible implementation would be to set/clear the group data observer on the children depending on whether isExpanded is true/false. Then all of the following code that checks if child change dispatches should fire could be deleted.

Comment (lisawray) [inline groupie/src/main/java/com/genius/groupie/ExpandableGroup.java]: That could definitely work as well. I don't have a strong feeling which I prefer
